services:
  - type: web
    name: aari-backend
    runtime: python
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PORT
        value: 8080
    autoDeploy: true
